// Tests for the egress lint.
//
// The scanner is a PARSER walk, not a pattern match, so most of these assert properties that
// are true by construction — the tests exist to prove the construction is the one claimed, and
// to lock the specific defects three reviewers found in the earlier regex/strip design:
//
//   1. delimiter-truncated extraction let "…/2000/svg;payload" reduce to an allowlisted URI
//   2. comment stripping ran before lexing and could blank a real URL, or a whole file
//   3. an HTML comment marker inside <script> hid code that genuinely executes
//   4. "https:" + "//host" defeated it entirely
//
// Cases 1-4 are now impossible rather than merely tested for, but they are tested anyway: a
// future rewrite that reintroduces any of them goes red here.

import { readFileSync, mkdtempSync, writeFileSync, rmSync, mkdirSync, existsSync, readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import {
  RECOGNISED_NAMESPACE_URIS,
  collectJsValues,
  loadAllowlist,
  scanDist,
  scanText,
} from './assert-no-external-hosts.mjs';
import {
  VENDOR_URL_NEUTRALIZATIONS,
  applyNeutralizations,
  staleRules,
} from './vendor-url-neutralization.ts';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REAL_ALLOWLIST = join(SCRIPT_DIR, 'external-host-allowlist.json');
const DIST = join(SCRIPT_DIR, '..', 'dist');

const { allowed } = loadAllowlist(REAL_ALLOWLIST);
const urls = (findings) => findings.map((f) => f.value);

/** A licence banner of exactly the shape esbuild preserves, URL and all. */
const LICENCE_BANNER = `/**
 * @license Example Library v1.2.3
 * Copyright (c) Example Authors.
 * Homepage: https://example.invalid/library
 * Released under the MIT licence.
 */
`;

/** The bundled-inline-SVG shape React emits for <svg xmlns="…/2000/svg">. */
const INLINE_SVG_PROPS = `jsx("svg",{xmlns:"http://www.w3.org/2000/svg",viewBox:"0 0 32 32"});`;

describe('positive case — a clean build carrying both known false-positive sources passes', () => {
  it('accepts a bundle with a licence-banner URL and an inline-SVG xmlns', () => {
    const bundle = `${LICENCE_BANNER}const a=1;${INLINE_SVG_PROPS}\n// see https://example.invalid/docs\n`;
    expect(scanText(bundle, 'js', allowed)).toEqual([]);
  });

  it('accepts an emitted SVG asset with an XML comment and namespaced attributes', () => {
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <!-- generated by a tool: https://example.invalid/tool -->
  <use xlink:href="#mark"/>
</svg>`;
    expect(scanText(svg, 'markup', allowed)).toEqual([]);
  });

  it('accepts CSS whose licence comment carries a URL', () => {
    const css = `/*! inter-latin-400 — https://example.invalid/fonts */
@font-face{font-family:Inter;src:url(./inter-400.woff2) format("woff2")}`;
    expect(scanText(css, 'css', allowed)).toEqual([]);
  });

  it('accepts relative and data URLs', () => {
    expect(scanText('const a=["/v1/aperture/threads","./x.png","data:image/svg+xml;base64,AA"];', 'js', allowed)).toEqual([]);
  });
});

describe('defect 1 — extraction is exact: no delimiter truncation', () => {
  it('fails a namespace with a semicolon-delimited payload', () => {
    // The old extractor stopped at ";" and matched the allowlist exactly. This is the case
    // that proved a passing five-lookalike suite could still be unsound.
    expect(urls(scanText('const n="http://www.w3.org/2000/svg;payload";', 'js', allowed)))
      .toEqual(['http://www.w3.org/2000/svg;payload']);
  });

  it('fails a namespace with a query string', () => {
    expect(scanText('fetch("http://www.w3.org/2000/svg?exfil=1");', 'js', allowed)).toHaveLength(1);
  });

  it('fails a namespace with a fragment', () => {
    expect(scanText('const n="http://www.w3.org/2000/svg#x";', 'js', allowed)).toHaveLength(1);
  });

  it('fails a namespace with trailing punctuation the old stripper removed', () => {
    for (const suffix of ['.', ',', ':', ';', '!', '?']) {
      expect(scanText(`const n="http://www.w3.org/2000/svg${suffix}";`, 'js', allowed)).toHaveLength(1);
    }
  });

  it('fails a prefix lookalike and a host lookalike', () => {
    expect(scanText('const n="http://www.w3.org/2000/svgx";', 'js', allowed)).toHaveLength(1);
    expect(scanText('const n="http://www.w3.org.evil.invalid/2000/svg";', 'js', allowed)).toHaveLength(1);
  });

  it('fails a userinfo disguise carrying an allowlisted path', () => {
    expect(scanText('fetch("http://user:<email>/2000/svg");', 'js', allowed)).toHaveLength(1);
  });

  it('fails an allowlisted namespace over a different scheme', () => {
    expect(scanText('const n="https://www.w3.org/2000/svg";', 'js', allowed)).toHaveLength(1);
  });

  it('fails a longer string that merely CONTAINS an allowlisted namespace', () => {
    expect(scanText('const n="http://www.w3.org/2000/svg and http://evil.invalid";', 'js', allowed)).toHaveLength(1);
  });
});

describe('defect 2 — comments cannot hide a URL, because the scanner parses', () => {
  it('ignores a line comment, a block comment and an HTML comment', () => {
    expect(scanText('const a=1; // https://example.invalid/notes', 'js', allowed)).toEqual([]);
    expect(scanText('/* https://example.invalid */ const a=1;', 'js', allowed)).toEqual([]);
    expect(scanText('<!-- https://example.invalid -->\n<div></div>', 'markup', allowed)).toEqual([]);
  });

  it('still sees a URL in a string that CONTAINS "//" before it', () => {
    // The old stripper blanked from the "//" onwards and went blind here.
    const src = 'const v = "prefix // https://evil.invalid";';
    expect(scanText(src, 'js', allowed)).toHaveLength(1);
  });

  it('still sees a URL after a regex literal containing "//"', () => {
    // The old stripper could blank the remainder of the file from a regex like this.
    const src = 'const r = /a\\/\\/b/g; fetch("https://evil.invalid");';
    expect(urls(scanText(src, 'js', allowed))).toEqual(['https://evil.invalid']);
  });

  it('still sees a URL after a regex literal containing a quote', () => {
    expect(urls(scanText('const r=/"/g; fetch("https://evil.invalid");', 'js', allowed)))
      .toEqual(['https://evil.invalid']);
  });

  it('does not treat a regex literal source as a scannable string', () => {
    expect(scanText('const r = /https:\\/\\/example\\.invalid/;', 'js', allowed)).toEqual([]);
  });

  it('sees a URL on the same line as a trailing comment', () => {
    expect(urls(scanText('fetch("https://evil.invalid"); // note', 'js', allowed)))
      .toEqual(['https://evil.invalid']);
  });
});

describe('defect 3 — an HTML comment marker inside <script> cannot hide executable code', () => {
  it('flags a fetch wrapped in Annex-B comment markers', () => {
    const html = `<html><body><script><!--
fetch("https://evil.invalid");
--></script></body></html>`;
    expect(urls(scanText(html, 'markup', allowed))).toEqual(['https://evil.invalid']);
  });

  it('flags a CDN src on a script tag', () => {
    expect(urls(scanText('<script src="https://cdn.example.invalid/x.js"></script>', 'markup', allowed)))
      .toEqual(['https://cdn.example.invalid/x.js']);
  });

  it('flags a remote font inside an inline <style>', () => {
    const html = '<html><head><style>@font-face{src:url(https://fonts.example.invalid/i.woff2)}</style></head></html>';
    expect(scanText(html, 'markup', allowed)).toHaveLength(1);
  });

  it('flags a URL in an embedded JSON script block', () => {
    const html = '<script type="application/json">{"endpoint":"https://evil.invalid"}</script>';
    expect(urls(scanText(html, 'markup', allowed))).toEqual(['https://evil.invalid']);
  });

  it('does NOT flag a script tag that is itself inside a comment', () => {
    // Inert by the same left-to-right ordering the HTML tokenizer uses.
    expect(scanText('<!-- <script src="https://cdn.example.invalid/x.js"></script> -->', 'markup', allowed)).toEqual([]);
  });
});

describe('defect 4 — statically-concatenated origins are folded, then caught', () => {
  it('folds "https:" + "//host"', () => {
    expect(urls(scanText('const u="https:"+"//evil.invalid";', 'js', allowed)))
      .toContain('https://evil.invalid');
  });

  it('folds a multi-part concatenation', () => {
    expect(scanText('const u="ht"+"tps://"+"evil"+".invalid/x";', 'js', allowed).length).toBeGreaterThan(0);
  });

  it('folds a template literal with no holes', () => {
    expect(scanText('const u=`https://evil.invalid/x`;', 'js', allowed)).toHaveLength(1);
  });

  it('folds a template literal whose holes are themselves static', () => {
    expect(scanText('const u=`https://${"evil"}.invalid`;', 'js', allowed).length).toBeGreaterThan(0);
  });

  it('does not report a scheme whose host is a genuine runtime hole', () => {
    // Runtime construction is explicitly out of a static scanner's reach — that is what the
    // CSP is for. Reporting it would be noise; pretending it is covered would be a lie.
    expect(scanText('const u=`https://${host}/x`;', 'js', allowed)).toEqual([]);
  });

  it('still finds a string literal nested inside a concatenation', () => {
    const values = collectJsValues('const u = f("https://evil.invalid") + "/x";').map((v) => v.value);
    expect(values).toContain('https://evil.invalid');
  });
});

describe('protocol-relative origins', () => {
  it('flags //host.tld at the head of a value', () => {
    expect(scanText('const u="//cdn.example.invalid/x.js";', 'js', allowed)).toHaveLength(1);
  });

  it('does not flag an ordinary path', () => {
    expect(scanText('const u="/v1/aperture/threads";', 'js', allowed)).toEqual([]);
  });
});

describe('unparseable assets fail closed', () => {
  it('reports a JavaScript asset it cannot parse', () => {
    const findings = scanText('function ( { !!!', 'js', allowed);
    expect(findings).toHaveLength(1);
    expect(findings[0].value).toMatch(/unparseable JavaScript/);
  });

  it('reports a JSON asset it cannot parse', () => {
    expect(urls(scanText('{not json', 'data', allowed))[0]).toMatch(/unparseable JSON/);
  });
});

describe('allowlist validation', () => {
  const withTemp = (doc, fn) => {
    const dir = mkdtempSync(join(tmpdir(), 'aptr01-allow-'));
    const file = join(dir, 'allowlist.json');
    writeFileSync(file, JSON.stringify(doc));
    try {
      fn(file);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  };

  it('rejects an EMPTY entries array rather than allowing everything', () => {
    withTemp({ entries: [] }, (file) => {
      expect(() => loadAllowlist(file)).toThrow(/zero entries/);
    });
  });

  it('rejects an entry with no reason', () => {
    withTemp({ entries: [{ uri: 'http://www.w3.org/2000/svg' }] }, (file) => {
      expect(() => loadAllowlist(file)).toThrow(/reason/);
    });
  });

  it('rejects an entry with an empty reason', () => {
    withTemp({ entries: [{ uri: 'http://www.w3.org/2000/svg', reason: '   ' }] }, (file) => {
      expect(() => loadAllowlist(file)).toThrow(/reason/);
    });
  });

  it('rejects a CDN — configuration cannot widen the namespace registry', () => {
    withTemp({ entries: [{ uri: 'https://cdn.example.invalid/lib.js', reason: 'convenience' }] }, (file) => {
      expect(() => loadAllowlist(file)).toThrow(/not a recognised XML\/HTML namespace/);
    });
  });

  it('rejects a non-namespace path on the namespace HOST', () => {
    withTemp({ entries: [{ uri: 'https://www.w3.org/not-a-namespace.js', reason: 'looks official' }] }, (file) => {
      expect(() => loadAllowlist(file)).toThrow(/not a recognised XML\/HTML namespace/);
    });
  });

  it('rejects a userinfo form of a recognised namespace', () => {
    withTemp({ entries: [{ uri: 'http://user:<email>/2000/svg', reason: 'svg' }] }, (file) => {
      expect(() => loadAllowlist(file)).toThrow(/not a recognised XML\/HTML namespace/);
    });
  });

  it('rejects a duplicate entry', () => {
    const e = { uri: 'http://www.w3.org/2000/svg', reason: 'svg' };
    withTemp({ entries: [e, e] }, (file) => {
      expect(() => loadAllowlist(file)).toThrow(/duplicate/i);
    });
  });

  it('rejects an unexpected field', () => {
    withTemp({ entries: [{ uri: 'http://www.w3.org/2000/svg', reason: 'svg', force: true }] }, (file) => {
      expect(() => loadAllowlist(file)).toThrow(/unexpected field/);
    });
  });

  it('rejects a malformed document rather than allowing everything', () => {
    withTemp({ allow: [] }, (file) => {
      expect(() => loadAllowlist(file)).toThrow(/entries/);
    });
  });

  it('the shipped allowlist is a subset of the code-owned namespace registry, all with reasons', () => {
    const doc = JSON.parse(readFileSync(REAL_ALLOWLIST, 'utf8'));
    expect(doc.entries.length).toBeGreaterThan(0);
    for (const entry of doc.entries) {
      expect(RECOGNISED_NAMESPACE_URIS).toContain(entry.uri);
      expect(entry.reason.trim().length).toBeGreaterThan(0);
    }
  });

  it('every recognised namespace URI is a bare w3.org namespace, not a fetchable resource', () => {
    for (const uri of RECOGNISED_NAMESPACE_URIS) {
      const parsed = new URL(uri);
      expect(parsed.host).toBe('www.w3.org');
      expect(parsed.username).toBe('');
      expect(parsed.search).toBe('');
      expect(parsed.hash).toBe('');
    }
  });
});

describe('vendor URL neutralization (react-dom scoping + behaviour)', () => {
  // Faithful replica of react-dom's minified formatProdErrorMessage.
  const REACT_DOM_FIXTURE = 'function fmt(e){for(var t="https://reactjs.org/docs/error-decoder.html?invariant='
    + '"+e,n=1;n<arguments.length;n++)t+="&args[]="+encodeURIComponent(arguments[n]);'
    + 'return"Minified React error #"+e+"; visit "+t+" for the full message.";}';
  const REACT_DOM_ID = '/repo/client/node_modules/react-dom/cjs/react-dom.production.min.js';

  // eslint-disable-next-line no-new-func -- the fixture is defined above, not external input
  const evalFmt = (code) => new Function(`${code}; return fmt;`)();

  it('is scoped: a chunk WITHOUT react-dom is left untouched', () => {
    const result = applyNeutralizations(REACT_DOM_FIXTURE, ['/repo/client/src/App.tsx']);
    expect(result.applied).toEqual([]);
    expect(result.code).toBe(REACT_DOM_FIXTURE);
  });

  it('applies to a chunk containing react-dom, and removes the external origin', () => {
    const result = applyNeutralizations(REACT_DOM_FIXTURE, [REACT_DOM_ID]);
    expect(result.applied).toHaveLength(1);
    expect(result.code).not.toContain('reactjs.org');
    expect(scanText(result.code, 'js', allowed)).toEqual([]);
  });

  it('REGRESSION: React error decoding still behaves after the replacement', () => {
    const before = evalFmt(REACT_DOM_FIXTURE)(418, 'Foo', 'Bar');
    const after = evalFmt(applyNeutralizations(REACT_DOM_FIXTURE, [REACT_DOM_ID]).code)(418, 'Foo', 'Bar');

    // The invariant number, the args, and the message shape all survive…
    expect(after).toContain('Minified React error #418');
    expect(after).toContain('invariant=418');
    expect(after).toContain('&args[]=Foo');
    expect(after).toContain('&args[]=Bar');
    expect(after).toContain('for the full message.');
    // …and the ONLY difference is the origin that was removed.
    expect(before).toContain('https://reactjs.org/docs/error-decoder.html?invariant=418');
    expect(after).not.toContain('reactjs.org');
    expect(after).toBe(before.replace(
      'https://reactjs.org/docs/error-decoder.html?invariant=',
      'react-error-decoder?invariant=',
    ));
  });

  it('handles a Windows-style module id', () => {
    const result = applyNeutralizations(REACT_DOM_FIXTURE, ['C:\\repo\\node_modules\\react-dom\\index.js']);
    expect(result.applied).toHaveLength(1);
  });

  it('reports a rule that fired as not stale, and one that never fired as stale', () => {
    expect(staleRules(new Set(VENDOR_URL_NEUTRALIZATIONS.map((r) => r.find)))).toEqual([]);
    expect(staleRules(new Set())).toHaveLength(VENDOR_URL_NEUTRALIZATIONS.length);
  });

  it('every rule is scoped to a module and carries a reason', () => {
    for (const rule of VENDOR_URL_NEUTRALIZATIONS) {
      expect(rule.module).toMatch(/node_modules\//);
      expect(rule.reason.trim().length).toBeGreaterThan(0);
    }
  });
});

describe('scanDist', () => {
  it('walks a build directory, skips binaries, and reports file and line', () => {
    const dir = mkdtempSync(join(tmpdir(), 'aptr01-dist-'));
    try {
      mkdirSync(join(dir, 'assets'));
      writeFileSync(join(dir, 'index.html'), '<!doctype html><div id="root"></div>');
      writeFileSync(join(dir, 'assets', 'clean.js'), `${LICENCE_BANNER}${INLINE_SVG_PROPS}`);
      writeFileSync(join(dir, 'assets', 'font.woff2'), Buffer.from([0x77, 0x4f, 0x46, 0x32]));
      const clean = scanDist(dir, allowed);
      expect(clean.findings).toEqual([]);
      expect(clean.scanned).toBe(2);

      writeFileSync(join(dir, 'assets', 'dirty.js'), 'x\nfetch("https://example.invalid")');
      const dirty = scanDist(dir, allowed);
      expect(dirty.findings).toHaveLength(1);
      expect(dirty.findings[0]).toMatchObject({ line: 2, value: 'https://example.invalid' });
      expect(dirty.findings[0].file).toContain('dirty.js');
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe('the real built bundle', () => {
  const built = existsSync(DIST);
  const bundleJs = () => readdirSync(join(DIST, 'assets'))
    .filter((f) => f.endsWith('.js'))
    .map((f) => readFileSync(join(DIST, 'assets', f), 'utf8'))
    .join('\n');

  it.skipIf(!built)('is clean under the lint', () => {
    expect(scanDist(DIST, allowed).findings).toEqual([]);
  });

  it.skipIf(!built)('still carries both known false-positive sources, so the lint stays exercised', () => {
    const js = bundleJs();
    expect(js).toContain('http://www.w3.org/2000/svg'); // inline-SVG xmlns
    expect(js).toMatch(/\/\*![^*]*https?:\/\//); // licence banner carrying a URL
  });

  it.skipIf(!built)('carries no react-dom documentation origin', () => {
    const js = bundleJs();
    expect(js).not.toContain('reactjs.org');
    expect(js).toContain('react-error-decoder?invariant=');
  });
});
