// Tests for the egress gate. These encode the review defect the gate was rewritten to fix:
// a naive grep FAILS a clean build (licence-banner URLs, SVG xmlns) while its negative test
// still passes — red on green. So the positive case here is as load-bearing as the negatives.

import { readFileSync, mkdtempSync, writeFileSync, rmSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import {
  loadAllowlist,
  scanText,
  scanDist,
  stripComments,
} from './assert-no-external-hosts.mjs';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REAL_ALLOWLIST = join(SCRIPT_DIR, 'external-host-allowlist.json');

const { allowed } = loadAllowlist(REAL_ALLOWLIST);

/** A licence banner of exactly the shape esbuild preserves, URL and all. */
const LICENCE_BANNER = `/**
 * @license Example Library v1.2.3
 * Copyright (c) Example Authors.
 * Homepage: https://example.invalid/library
 * Released under the MIT licence.
 */
`;

/** The bundled-inline-SVG shape React emits for <svg xmlns="…/2000/svg">. */
const INLINE_SVG_PROPS = `jsx("svg",{xmlns:"http://www.w3.org/2000/svg",viewBox:"0 0 32 32"});`;

describe('positive case — a clean build with BOTH known false-positive sources passes', () => {
  it('accepts a bundle carrying a licence-banner URL and an inline-SVG xmlns', () => {
    const bundle = `${LICENCE_BANNER}const a=1;${INLINE_SVG_PROPS}\n// see https://example.invalid/docs for details\n`;
    expect(scanText(bundle, 'js', allowed)).toEqual([]);
  });

  it('accepts a real emitted SVG asset with an XML comment and namespaced attributes', () => {
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <!-- generated by a tool: https://example.invalid/tool -->
  <use xlink:href="#mark"/>
</svg>`;
    expect(scanText(svg, 'markup', allowed)).toEqual([]);
  });

  it('accepts CSS whose licence comment carries a URL', () => {
    const css = `/*! inter-latin-400 — https://example.invalid/fonts */
@font-face{font-family:Inter;src:url(./inter-400.woff2) format("woff2")}`;
    expect(scanText(css, 'css', allowed)).toEqual([]);
  });
});

describe('negative case 1 — a real external fetch fails the gate', () => {
  it('flags fetch("https://example.invalid")', () => {
    const findings = scanText(`async function load(){return fetch("https://example.invalid")}`, 'js', allowed);
    expect(findings).toHaveLength(1);
    expect(findings[0].url).toBe('https://example.invalid');
  });

  it('flags a CDN <script src> in emitted markup', () => {
    const findings = scanText('<script src="https://cdn.example.invalid/x.js"></script>', 'markup', allowed);
    expect(findings.map((f) => f.url)).toEqual(['https://cdn.example.invalid/x.js']);
  });

  it('flags a remote @font-face src in emitted CSS', () => {
    const findings = scanText('@font-face{src:url(https://fonts.example.invalid/i.woff2)}', 'css', allowed);
    expect(findings).toHaveLength(1);
  });

  it('reports the asset line number of the violation', () => {
    const findings = scanText(`${LICENCE_BANNER}const a=1;\nfetch("https://example.invalid/x");`, 'js', allowed);
    expect(findings).toHaveLength(1);
    expect(findings[0].line).toBe(8);
  });
});

describe('negative case 2 — a URL that exists only inside a comment does NOT fail', () => {
  it('ignores a line comment', () => {
    expect(scanText('const a=1; // https://example.invalid/notes', 'js', allowed)).toEqual([]);
  });

  it('ignores a block comment', () => {
    expect(scanText('/* https://example.invalid/notes */ const a=1;', 'js', allowed)).toEqual([]);
  });

  it('ignores an HTML comment', () => {
    expect(scanText('<!-- https://example.invalid -->\n<div></div>', 'markup', allowed)).toEqual([]);
  });

  it('does NOT let comment stripping swallow a violation on the same line', () => {
    // The dangerous inverse: treating the "//" of a URL as a comment start would delete the
    // very violation the gate exists to catch.
    const findings = scanText('fetch("https://example.invalid"); // trailing note', 'js', allowed);
    expect(findings.map((f) => f.url)).toEqual(['https://example.invalid']);
  });
});

describe('negative case 3 — allowlist matching is EXACT, never prefix or substring', () => {
  it('fails a URI that extends an allowlisted namespace', () => {
    const findings = scanText('const ns="http://www.w3.org/2000/svgx";', 'js', allowed);
    expect(findings.map((f) => f.url)).toEqual(['http://www.w3.org/2000/svgx']);
  });

  it('fails a lookalike host that merely starts the same way', () => {
    const findings = scanText('const ns="http://www.w3.org.evil.invalid/2000/svg";', 'js', allowed);
    expect(findings).toHaveLength(1);
  });

  it('fails an allowlisted namespace carrying a query string', () => {
    const findings = scanText('fetch("http://www.w3.org/2000/svg?exfil=1");', 'js', allowed);
    expect(findings.map((f) => f.url)).toEqual(['http://www.w3.org/2000/svg?exfil=1']);
  });

  it('fails an allowlisted namespace over a different scheme', () => {
    expect(scanText('const ns="https://www.w3.org/2000/svg";', 'js', allowed)).toHaveLength(1);
  });

  it('fails a deeper path under an allowlisted namespace', () => {
    expect(scanText('fetch("http://www.w3.org/2000/svg/payload.js");', 'js', allowed)).toHaveLength(1);
  });
});

describe('allowlist validation', () => {
  const withTemp = (doc, fn) => {
    const dir = mkdtempSync(join(tmpdir(), 'aptr01-allow-'));
    const file = join(dir, 'allowlist.json');
    writeFileSync(file, JSON.stringify(doc));
    try {
      fn(file);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  };

  it('rejects an entry with no reason', () => {
    withTemp({ entries: [{ uri: 'http://www.w3.org/2000/svg' }] }, (file) => {
      expect(() => loadAllowlist(file)).toThrow(/reason/);
    });
  });

  it('rejects an entry with an empty reason', () => {
    withTemp({ entries: [{ uri: 'http://www.w3.org/2000/svg', reason: '   ' }] }, (file) => {
      expect(() => loadAllowlist(file)).toThrow(/reason/);
    });
  });

  it('rejects a non-namespace entry (a CDN cannot be config-allowlisted)', () => {
    withTemp({ entries: [{ uri: 'https://cdn.example.invalid/lib.js', reason: 'convenience' }] }, (file) => {
      expect(() => loadAllowlist(file)).toThrow(/namespace/);
    });
  });

  it('rejects a duplicate entry', () => {
    const e = { uri: 'http://www.w3.org/2000/svg', reason: 'svg' };
    withTemp({ entries: [e, e] }, (file) => {
      expect(() => loadAllowlist(file)).toThrow(/duplicate/i);
    });
  });

  it('rejects a malformed document rather than allowing everything', () => {
    withTemp({ allow: [] }, (file) => {
      expect(() => loadAllowlist(file)).toThrow(/entries/);
    });
  });

  it('the shipped allowlist contains only reason-annotated W3C namespace URIs', () => {
    const doc = JSON.parse(readFileSync(REAL_ALLOWLIST, 'utf8'));
    expect(doc.entries.length).toBeGreaterThan(0);
    for (const entry of doc.entries) {
      expect(entry.reason.trim().length).toBeGreaterThan(0);
      expect(new URL(entry.uri).host).toBe('www.w3.org');
    }
  });
});

describe('comment stripping', () => {
  it('is idempotent', () => {
    const src = `${LICENCE_BANNER}const a="https://example.invalid";`;
    const once = stripComments(src, 'js');
    expect(stripComments(once, 'js')).toBe(once);
  });

  it('tolerates input with zero comments (already minified)', () => {
    const src = 'const a=1;const b=2;';
    expect(stripComments(src, 'js')).toBe(src);
  });

  it('preserves line count so reported line numbers stay accurate', () => {
    const src = 'a\n/* x\ny\nz */\nb';
    expect(stripComments(src, 'js').split('\n')).toHaveLength(src.split('\n').length);
  });

  it('does not mistake a regex literal containing a quote for a string', () => {
    const src = `const r=/"/g; fetch("https://example.invalid");`;
    expect(scanText(src, 'js', allowed).map((f) => f.url)).toEqual(['https://example.invalid']);
  });

  it('sees a URL built inside a template literal', () => {
    const src = 'const u=`https://example.invalid/${id}`;';
    expect(scanText(src, 'js', allowed).length).toBeGreaterThan(0);
  });
});

describe('scanDist', () => {
  it('walks a build directory, skips binaries, and reports file and line', () => {
    const dir = mkdtempSync(join(tmpdir(), 'aptr01-dist-'));
    try {
      mkdirSync(join(dir, 'assets'));
      writeFileSync(join(dir, 'index.html'), '<!doctype html><div id="root"></div>');
      writeFileSync(join(dir, 'assets', 'clean.js'), `${LICENCE_BANNER}${INLINE_SVG_PROPS}`);
      writeFileSync(join(dir, 'assets', 'font.woff2'), Buffer.from([0x77, 0x4f, 0x46, 0x32]));
      const clean = scanDist(dir, allowed);
      expect(clean.findings).toEqual([]);
      expect(clean.scanned).toBe(2);

      writeFileSync(join(dir, 'assets', 'dirty.js'), 'x\nfetch("https://example.invalid")');
      const dirty = scanDist(dir, allowed);
      expect(dirty.findings).toHaveLength(1);
      expect(dirty.findings[0]).toMatchObject({ line: 2, url: 'https://example.invalid' });
      expect(dirty.findings[0].file).toContain('dirty.js');
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});
