// Tests for the egress lint.
//
// The scanner is a PARSER walk, not a pattern match, so most of these assert properties that
// are true by construction — the tests exist to prove the construction is the one claimed, and
// to lock the specific defects three reviewers found in the earlier regex/strip design:
//
//   1. delimiter-truncated extraction let "…/2000/svg;payload" reduce to an allowlisted URI
//   2. comment stripping ran before lexing and could blank a real URL, or a whole file
//   3. an HTML comment marker inside <script> hid code that genuinely executes
//   4. "https:" + "//host" defeated it entirely
//
// Cases 1-4 are now impossible rather than merely tested for, but they are tested anyway: a
// future rewrite that reintroduces any of them goes red here.

import { readFileSync, mkdtempSync, writeFileSync, rmSync, mkdirSync, existsSync, readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import {
  RECOGNISED_NAMESPACE_URIS,
  collectJsValues,
  identifyBinaryFormat,
  loadAllowlist,
  scanDist,
  scanText,
} from './assert-no-external-hosts.mjs';
import {
  VENDOR_URL_NEUTRALIZATIONS,
  applyNeutralizations,
  staleRules,
} from './vendor-url-neutralization.ts';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REAL_ALLOWLIST = join(SCRIPT_DIR, 'external-host-allowlist.json');
const DIST = join(SCRIPT_DIR, '..', 'dist');

const { allowed } = loadAllowlist(REAL_ALLOWLIST);
const urls = (findings) => findings.map((f) => f.value);

/** A licence banner of exactly the shape esbuild preserves, URL and all. */
const LICENCE_BANNER = `/**
 * @license Example Library v1.2.3
 * Copyright (c) Example Authors.
 * Homepage: https://example.invalid/library
 * Released under the MIT licence.
 */
`;

/** The bundled-inline-SVG shape React emits for <svg xmlns="…/2000/svg">. */
const INLINE_SVG_PROPS = `jsx("svg",{xmlns:"http://www.w3.org/2000/svg",viewBox:"0 0 32 32"});`;

describe('positive case — a clean build carrying both known false-positive sources passes', () => {
  it('accepts a bundle with a licence-banner URL and an inline-SVG xmlns', () => {
    const bundle = `${LICENCE_BANNER}const a=1;${INLINE_SVG_PROPS}\n// see https://example.invalid/docs\n`;
    expect(scanText(bundle, 'js', allowed)).toEqual([]);
  });

  it('accepts an emitted SVG asset with an XML comment and namespaced attributes', () => {
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <!-- generated by a tool: https://example.invalid/tool -->
  <use xlink:href="#mark"/>
</svg>`;
    expect(scanText(svg, 'markup', allowed)).toEqual([]);
  });

  it('accepts CSS whose licence comment carries a URL', () => {
    const css = `/*! inter-latin-400 — https://example.invalid/fonts */
@font-face{font-family:Inter;src:url(./inter-400.woff2) format("woff2")}`;
    expect(scanText(css, 'css', allowed)).toEqual([]);
  });

  it('accepts relative and data URLs', () => {
    expect(scanText('const a=["/v1/aperture/threads","./x.png","data:image/svg+xml;base64,AA"];', 'js', allowed)).toEqual([]);
  });
});

describe('defect 1 — extraction is exact: no delimiter truncation', () => {
  it('fails a namespace with a semicolon-delimited payload', () => {
    // The old extractor stopped at ";" and matched the allowlist exactly. This is the case
    // that proved a passing five-lookalike suite could still be unsound.
    expect(urls(scanText('const n="http://www.w3.org/2000/svg;payload";', 'js', allowed)))
      .toEqual(['http://www.w3.org/2000/svg;payload']);
  });

  it('fails a namespace with a query string', () => {
    expect(scanText('fetch("http://www.w3.org/2000/svg?exfil=1");', 'js', allowed)).toHaveLength(1);
  });

  it('fails a namespace with a fragment', () => {
    expect(scanText('const n="http://www.w3.org/2000/svg#x";', 'js', allowed)).toHaveLength(1);
  });

  it('fails a namespace with trailing punctuation the old stripper removed', () => {
    for (const suffix of ['.', ',', ':', ';', '!', '?']) {
      expect(scanText(`const n="http://www.w3.org/2000/svg${suffix}";`, 'js', allowed)).toHaveLength(1);
    }
  });

  it('fails a prefix lookalike and a host lookalike', () => {
    expect(scanText('const n="http://www.w3.org/2000/svgx";', 'js', allowed)).toHaveLength(1);
    expect(scanText('const n="http://www.w3.org.evil.invalid/2000/svg";', 'js', allowed)).toHaveLength(1);
  });

  it('fails a userinfo disguise carrying an allowlisted path', () => {
    expect(scanText('fetch("http://user:<email>/2000/svg");', 'js', allowed)).toHaveLength(1);
  });

  it('fails an allowlisted namespace over a different scheme', () => {
    expect(scanText('const n="https://www.w3.org/2000/svg";', 'js', allowed)).toHaveLength(1);
  });

  it('fails a longer string that merely CONTAINS an allowlisted namespace', () => {
    expect(scanText('const n="http://www.w3.org/2000/svg and http://evil.invalid";', 'js', allowed)).toHaveLength(1);
  });
});

describe('defect 2 — comments cannot hide a URL, because the scanner parses', () => {
  it('ignores a line comment, a block comment and an HTML comment', () => {
    expect(scanText('const a=1; // https://example.invalid/notes', 'js', allowed)).toEqual([]);
    expect(scanText('/* https://example.invalid */ const a=1;', 'js', allowed)).toEqual([]);
    expect(scanText('<!-- https://example.invalid -->\n<div></div>', 'markup', allowed)).toEqual([]);
  });

  it('still sees a URL in a string that CONTAINS "//" before it', () => {
    // The old stripper blanked from the "//" onwards and went blind here.
    const src = 'const v = "prefix // https://evil.invalid";';
    expect(scanText(src, 'js', allowed)).toHaveLength(1);
  });

  it('still sees a URL after a regex literal containing "//"', () => {
    // The old stripper could blank the remainder of the file from a regex like this.
    const src = 'const r = /a\\/\\/b/g; fetch("https://evil.invalid");';
    expect(urls(scanText(src, 'js', allowed))).toEqual(['https://evil.invalid']);
  });

  it('still sees a URL after a regex literal containing a quote', () => {
    expect(urls(scanText('const r=/"/g; fetch("https://evil.invalid");', 'js', allowed)))
      .toEqual(['https://evil.invalid']);
  });

  it('does not treat a regex literal source as a scannable string', () => {
    expect(scanText('const r = /https:\\/\\/example\\.invalid/;', 'js', allowed)).toEqual([]);
  });

  it('sees a URL on the same line as a trailing comment', () => {
    expect(urls(scanText('fetch("https://evil.invalid"); // note', 'js', allowed)))
      .toEqual(['https://evil.invalid']);
  });
});

describe('defect 3 — an HTML comment marker inside <script> cannot hide executable code', () => {
  it('flags a fetch wrapped in Annex-B comment markers', () => {
    const html = `<html><body><script><!--
fetch("https://evil.invalid");
--></script></body></html>`;
    expect(urls(scanText(html, 'markup', allowed))).toEqual(['https://evil.invalid']);
  });

  it('flags a CDN src on a script tag', () => {
    expect(urls(scanText('<script src="https://cdn.example.invalid/x.js"></script>', 'markup', allowed)))
      .toEqual(['https://cdn.example.invalid/x.js']);
  });

  it('flags a remote font inside an inline <style>', () => {
    const html = '<html><head><style>@font-face{src:url(https://fonts.example.invalid/i.woff2)}</style></head></html>';
    expect(scanText(html, 'markup', allowed)).toHaveLength(1);
  });

  it('flags a URL in an embedded JSON script block', () => {
    const html = '<script type="application/json">{"endpoint":"https://evil.invalid"}</script>';
    expect(urls(scanText(html, 'markup', allowed))).toEqual(['https://evil.invalid']);
  });

  it('does NOT flag a script tag that is itself inside a comment', () => {
    // Inert by the same left-to-right ordering the HTML tokenizer uses.
    expect(scanText('<!-- <script src="https://cdn.example.invalid/x.js"></script> -->', 'markup', allowed)).toEqual([]);
  });
});

describe('defect 4 — statically-concatenated origins are folded, then caught', () => {
  it('folds "https:" + "//host"', () => {
    expect(urls(scanText('const u="https:"+"//evil.invalid";', 'js', allowed)))
      .toContain('https://evil.invalid');
  });

  it('folds a multi-part concatenation', () => {
    expect(scanText('const u="ht"+"tps://"+"evil"+".invalid/x";', 'js', allowed).length).toBeGreaterThan(0);
  });

  it('folds a template literal with no holes', () => {
    expect(scanText('const u=`https://evil.invalid/x`;', 'js', allowed)).toHaveLength(1);
  });

  it('folds a template literal whose holes are themselves static', () => {
    expect(scanText('const u=`https://${"evil"}.invalid`;', 'js', allowed).length).toBeGreaterThan(0);
  });

  it('does not report a scheme whose host is a genuine runtime hole', () => {
    // Runtime construction is explicitly out of a static scanner's reach — that is what the
    // CSP is for. Reporting it would be noise; pretending it is covered would be a lie.
    expect(scanText('const u=`https://${host}/x`;', 'js', allowed)).toEqual([]);
  });

  it('still finds a string literal nested inside a concatenation', () => {
    const values = collectJsValues('const u = f("https://evil.invalid") + "/x";').map((v) => v.value);
    expect(values).toContain('https://evil.invalid');
  });
});

describe('protocol-relative origins are validated as URLs, not by a dotted-host pattern', () => {
  it('flags a dotted host', () => {
    expect(scanText('const u="//cdn.example.invalid/x.js";', 'js', allowed)).toHaveLength(1);
  });

  it('flags a SINGLE-LABEL host', () => {
    expect(urls(scanText('const u="//localhost/api";', 'js', allowed))).toEqual(['//localhost/api']);
  });

  it('flags an IPv4 literal', () => {
    expect(urls(scanText('const u="//127.0.0.1/api";', 'js', allowed))).toEqual(['//127.0.0.1/api']);
  });

  it('flags an IPv6 literal', () => {
    expect(urls(scanText('const u="//[::1]/api";', 'js', allowed))).toEqual(['//[::1]/api']);
  });

  it('flags a host with a port', () => {
    expect(scanText('const u="//localhost:3000/api";', 'js', allowed)).toHaveLength(1);
  });

  it('flags one in markup and in CSS too', () => {
    expect(scanText('<script src="//localhost/x.js"></script>', 'markup', allowed)).toHaveLength(1);
    expect(scanText('@font-face{src:url(//127.0.0.1/i.woff2)}', 'css', allowed)).toHaveLength(1);
  });

  it('does not flag an ordinary path, a bare "//", or prose', () => {
    expect(scanText('const u="/v1/aperture/threads";', 'js', allowed)).toEqual([]);
    expect(scanText('const u="//";', 'js', allowed)).toEqual([]);
    expect(scanText('const u="// see the notes";', 'js', allowed)).toEqual([]);
  });
});

describe('unknown extensions fail closed, matching the documented claim', () => {
  const withDist = (files, fn) => {
    const dir = mkdtempSync(join(tmpdir(), 'aptr01-unknown-'));
    try {
      for (const [name, content] of Object.entries(files)) {
        writeFileSync(join(dir, name), content);
      }
      fn(dir);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  };

  it('reports an unrecognised TEXTUAL asset containing a URL instead of skipping it', () => {
    withDist({ 'data.unknown': 'endpoint = https://evil.invalid/collect\n' }, (dir) => {
      const result = scanDist(dir, allowed);
      expect(result.findings).toHaveLength(1);
      expect(result.findings[0].file).toBe('data.unknown');
      expect(result.findings[0].value).toMatch(/unscanned asset/);
    });
  });

  it('reports an unrecognised textual asset even when it contains no URL — silence must mean "looked"', () => {
    withDist({ 'notes.rst': 'nothing to see here' }, (dir) => {
      expect(scanDist(dir, allowed).findings).toHaveLength(1);
    });
  });

  it('skips a font that matches a known format signature', () => {
    const header = Buffer.alloc(64);
    header.write('wOF2', 0, 'latin1');
    header.writeUInt32BE(64, 8); // WOFF2 carries its total length at offset 8
    withDist({ 'f.woff2': header }, (dir) => {
      const result = scanDist(dir, allowed);
      expect(result.findings).toEqual([]);
      expect(result.skippedBinary).toBe(1);
    });
  });

  it('REPORTS a UTF-16 asset instead of mistaking its NUL bytes for binary', () => {
    // The defect: "no NULs" was used to infer text, so UTF-16 (full of NULs) read as binary and
    // was skipped. Skipping now requires a signature MATCH, so this is reported instead.
    withDist({ 'data.unknown': Buffer.from('https://evil.invalid/collect', 'utf16le') }, (dir) => {
      const result = scanDist(dir, allowed);
      expect(result.skippedBinary).toBe(0);
      expect(result.findings).toHaveLength(1);
      expect(result.findings[0].value).toMatch(/unscanned asset/);
    });
  });

  it('REPORTS an unrecognised extension whose content matches no approved binary format', () => {
    withDist({ 'blob.bin': Buffer.from([0x13, 0x37, 0x00, 0x42]) }, (dir) => {
      const result = scanDist(dir, allowed);
      expect(result.skippedBinary).toBe(0);
      expect(result.findings).toHaveLength(1);
    });
  });

  it('REPORTS a file whose extension claims binary but whose bytes do not', () => {
    // A mislabelled asset cannot buy silence with its name.
    withDist({ 'fake.png': 'https://evil.invalid/collect' }, (dir) => {
      expect(scanDist(dir, allowed).findings).toHaveLength(1);
    });
  });

  it('ADVERSARIAL: a textual asset starting with each format prefix is still reported', () => {
    // A signature that is only a printable prefix is not identification: a text file can start
    // with those same bytes. `PK` alone let `PKhttps://evil.invalid` be skipped as a ZIP.
    const decoys = [
      'PKhttps://evil.invalid',          // zip — needs the full \x03\x04 / \x05\x06 / \x07\x08
      'PKhttps://evil.invalid',    // …and a truncated one is still not a zip
      'wOFFhttps://evil.invalid',        // woff — needs a length field matching the file
      'wOF2https://evil.invalid',        // woff2 — same
      'OTTOhttps://evil.invalid',        // opentype — needs a coherent sfnt table header
      'GIF89ahttps://evil.invalid',      // gif — removed: any two non-zero bytes passed as dimensions
      'RIFFhttps://evil.invalidWEBP',    // webp — needs a size field consistent with the file
      'RIFFhttps://evil.invalidWAVE',    // wav — same
      '    ftyphttps://evil.invalid',    // isobmff — needs a plausible box size and known brand
      'ID3https://evil.invalid',         // mp3 — removed from the table entirely
      'OggShttps://evil.invalid',        // ogg — removed
      'fLaChttps://evil.invalid',        // flac — removed
      '%PDF-https://evil.invalid',       // pdf — removed
      'ttcfhttps://evil.invalid',        // font collection — removed
      'truehttps://evil.invalid',        // `true` sfnt variant — removed
      'BMhttps://evil.invalid',          // bmp — removed
    ];
    for (const decoy of decoys) {
      expect(identifyBinaryFormat(Buffer.from(decoy, 'latin1')), decoy).toBeNull();
    }
  });

  it('ADVERSARIAL: a decoy reaches the build report rather than being counted as binary', () => {
    withDist({ 'payload.unknown': 'PKhttps://evil.invalid/collect' }, (dir) => {
      const result = scanDist(dir, allowed);
      expect(result.skippedBinary).toBe(0);
      expect(result.findings).toHaveLength(1);
    });
  });

  // The two tests below RECORD a documented limitation. They are not assertions of desired
  // behaviour, and they must not be read as one: a signature identifies FORMAT, not INTENT, and
  // binary content is never scanned. Both cases are deliberate obfuscation, which this lint
  // delegates to the runtime CSP. Closing them would mean parsing container structure and
  // scanning printable strings inside binaries — a different and much larger tool. If either
  // outcome ever changes, update the recording and the NON-GOALS block together.

  it('OBSERVED LIMITATION (delegated to CSP): an asset crafted to carry a known signature is SKIPPED', () => {
    // Real PNG magic bytes, then an origin as the "image" body. Nothing about the bytes after
    // the signature is examined, so this is skipped and counted as binary.
    const crafted = Buffer.concat([
      Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
      Buffer.from('https://evil.invalid/collect', 'latin1'),
    ]);
    expect(identifyBinaryFormat(crafted)).toBe('png');
    withDist({ 'decoy.unknown': crafted }, (dir) => {
      const result = scanDist(dir, allowed);
      expect(result.findings).toEqual([]);
      expect(result.skippedBinary).toBe(1);
    });
  });

  it('OBSERVED LIMITATION (delegated to CSP): a genuine binary with an origin in trailing data is SKIPPED', () => {
    // A structurally valid WOFF2 header — length field and all — with an origin appended after
    // it, standing in for metadata or trailing data inside a real asset.
    const header = Buffer.alloc(64);
    header.write('wOF2', 0, 'latin1');
    header.writeUInt32BE(64, 8);
    const withTrailer = Buffer.concat([header, Buffer.from('https://evil.invalid/collect', 'latin1')]);
    // Note the header's length field no longer matches the file, so this particular shape is
    // reported; the same trailer INSIDE a correctly-sized asset would not be.
    expect(identifyBinaryFormat(withTrailer)).toBeNull();

    const consistent = Buffer.alloc(96);
    consistent.write('wOF2', 0, 'latin1');
    consistent.writeUInt32BE(96, 8);
    consistent.write('https://evil.invalid/collect', 48, 'latin1');
    expect(identifyBinaryFormat(consistent)).toBe('woff2');
    withDist({ 'font.unknown': consistent }, (dir) => {
      const result = scanDist(dir, allowed);
      expect(result.findings).toEqual([]);
      expect(result.skippedBinary).toBe(1);
    });
  });

  it('identifies each approved binary format from its complete signature', () => {
    /** A WOFF/WOFF2 header whose length field matches the buffer, as the spec requires. */
    const woff = (signature, size = 64) => {
      const b = Buffer.alloc(size);
      b.write(signature, 0, 'latin1');
      b.writeUInt32BE(size, 8);
      return b;
    };
    /** An sfnt header whose search fields agree with numTables. */
    const sfnt = (version) => {
      const b = Buffer.alloc(32);
      if (version === 'OTTO') b.write('OTTO', 0, 'latin1');
      else b.writeUInt32BE(0x00010000, 0);
      const numTables = 8;
      const exponent = Math.floor(Math.log2(numTables));
      b.writeUInt16BE(numTables, 4);
      b.writeUInt16BE(16 * 2 ** exponent, 6);
      b.writeUInt16BE(exponent, 8);
      b.writeUInt16BE(numTables * 16 - 16 * 2 ** exponent, 10);
      return b;
    };
    /** A RIFF container whose size field matches the buffer. */
    const riff = (formType, size = 64) => {
      const b = Buffer.alloc(size);
      b.write('RIFF', 0, 'latin1');
      b.writeUInt32LE(size - 8, 4);
      b.write(formType, 8, 'latin1');
      return b;
    };
    const isobmff = (brand) => {
      const b = Buffer.alloc(32);
      b.writeUInt32BE(32, 0);
      b.write('ftyp', 4, 'latin1');
      b.write(brand, 8, 'latin1');
      return b;
    };

    const samples = {
      woff: woff('wOFF'),
      woff2: woff('wOF2'),
      opentype: sfnt('OTTO'),
      truetype: sfnt('sfnt'),
      png: Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
      jpeg: Buffer.from([0xff, 0xd8, 0xff, 0xe0]),
      webp: riff('WEBP'),
      wav: riff('WAVE'),
      avif: isobmff('avif'),
      mp4: isobmff('isom'),
      ico: Buffer.from([0x00, 0x00, 0x01, 0x00, 0x01, 0x00]),
      matroska: Buffer.from([0x1a, 0x45, 0xdf, 0xa3, 0x00]),
      zip: Buffer.from([0x50, 0x4b, 0x03, 0x04, 0x14]),
      gzip: Buffer.from([0x1f, 0x8b, 0x08, 0x00]),
      wasm: Buffer.from([0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00]),
    };
    for (const [name, bytes] of Object.entries(samples)) {
      expect(identifyBinaryFormat(bytes), name).not.toBeNull();
    }
    expect(identifyBinaryFormat(Buffer.from('plain text', 'utf8'))).toBeNull();
    expect(identifyBinaryFormat(Buffer.from('utf16 text', 'utf16le'))).toBeNull();
  });
});

describe('multi-value attributes cannot hide a protocol-relative origin', () => {
  it('splits srcset and flags a candidate that is not the first', () => {
    const html = '<img src="/local.png" srcset="/local.png 1x, //localhost/collect 2x">';
    expect(urls(scanText(html, 'markup', allowed))).toEqual(['//localhost/collect']);
  });

  it('splits imagesrcset too', () => {
    const html = '<link rel="preload" imagesrcset="/a.png 1x, //127.0.0.1/b.png 2x">';
    expect(scanText(html, 'markup', allowed)).toHaveLength(1);
  });

  it('routes a style attribute through the CSS scanner', () => {
    const html = '<div style="background:url(//localhost/x); color:red"></div>';
    expect(urls(scanText(html, 'markup', allowed))).toEqual(['//localhost/x']);
  });

  it('still catches an absolute origin in both', () => {
    expect(scanText('<img srcset="/a.png 1x, https://cdn.example.invalid/b.png 2x">', 'markup', allowed)).toHaveLength(1);
    expect(scanText('<div style="background:url(https://cdn.example.invalid/x)"></div>', 'markup', allowed)).toHaveLength(1);
  });

  it('does not flag clean multi-value attributes', () => {
    expect(scanText('<img src="/a.png" srcset="/a.png 1x, /<email> 2x">', 'markup', allowed)).toEqual([]);
    expect(scanText('<div style="background:url(/bg.png); margin:0"></div>', 'markup', allowed)).toEqual([]);
  });

  it('also catches it in the JS bundle, where a srcSet prop is just a string', () => {
    // A React `srcSet` prop is emitted as one JavaScript string, so the markup-side splitting
    // never sees it. The value predicate itself has to give the protocol-relative form the
    // same reach an absolute origin already had.
    const js = 'jsx("img",{src:"/a.png",srcSet:"/a.png 1x, //localhost/collect 2x"});';
    expect(scanText(js, 'js', allowed)).toHaveLength(1);
  });

  it('does not flag a clean srcSet prop, prose, or a path with an embedded double slash', () => {
    expect(scanText('jsx("img",{srcSet:"/a.png 1x, /<email> 2x"});', 'js', allowed)).toEqual([]);
    expect(scanText('const s="see // the notes below";', 'js', allowed)).toEqual([]);
    expect(scanText('const s="a//b.c and /x//y";', 'js', allowed)).toEqual([]);
  });
});

describe('documented non-goals — recorded as accepted limitations, not silent gaps', () => {
  // These assertions exist so the limitation is VISIBLE in the suite. If a future change makes
  // any of them detected, the test goes red and the NON-GOALS block must be updated to match.
  // Every case here is covered by the runtime CSP (APTR-99), which is the actual control.

  it('does NOT decode HTML character references (accepted; CSP covers it)', () => {
    expect(scanText('<img src="&#x2F;&#x2F;evil.invalid/x.png">', 'markup', allowed)).toEqual([]);
  });

  it('does NOT decode CSS escapes (accepted; CSP covers it)', () => {
    expect(scanText('@font-face{src:url(\\68 ttps://evil.invalid/i.woff2)}', 'css', allowed)).toEqual([]);
  });

  // Detection after a ">" inside an attribute value is UNMODELLED — it may miss or garble.
  // These two tests pin the observed outcomes so the behaviour is recorded, NOT because either
  // outcome is specified. Do not turn them back into a general claim: three attempts to
  // characterise this precisely ("not detected", "unreliable in both directions", "always
  // garbled") were each disproved by a reviewer. If one of these flips, update the recording,
  // not the promise.
  it('OBSERVED (unmodelled): an origin after the desynchronizing ">" can be MISSED', () => {
    expect(scanText('<img alt="a>b" src=//localhost/x>', 'markup', allowed)).toEqual([]);
  });

  it('OBSERVED (unmodelled): or reported as a GARBLED fragment, not as the attribute value', () => {
    const findings = scanText('<div data-a="a>b" data-b="https://evil.invalid"></div>', 'markup', allowed);
    expect(findings).toHaveLength(1);
    expect(findings[0].value).toContain('https://evil.invalid');
    expect(findings[0].value).not.toBe('https://evil.invalid');
  });
});

describe('unparseable assets fail closed', () => {
  it('reports a JavaScript asset it cannot parse', () => {
    const findings = scanText('function ( { !!!', 'js', allowed);
    expect(findings).toHaveLength(1);
    expect(findings[0].value).toMatch(/unparseable JavaScript/);
  });

  it('reports a JSON asset it cannot parse', () => {
    expect(urls(scanText('{not json', 'data', allowed))[0]).toMatch(/unparseable JSON/);
  });
});

describe('allowlist validation', () => {
  const withTemp = (doc, fn) => {
    const dir = mkdtempSync(join(tmpdir(), 'aptr01-allow-'));
    const file = join(dir, 'allowlist.json');
    writeFileSync(file, JSON.stringify(doc));
    try {
      fn(file);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  };

  it('rejects an EMPTY entries array rather than allowing everything', () => {
    withTemp({ entries: [] }, (file) => {
      expect(() => loadAllowlist(file)).toThrow(/zero entries/);
    });
  });

  it('rejects an entry with no reason', () => {
    withTemp({ entries: [{ uri: 'http://www.w3.org/2000/svg' }] }, (file) => {
      expect(() => loadAllowlist(file)).toThrow(/reason/);
    });
  });

  it('rejects an entry with an empty reason', () => {
    withTemp({ entries: [{ uri: 'http://www.w3.org/2000/svg', reason: '   ' }] }, (file) => {
      expect(() => loadAllowlist(file)).toThrow(/reason/);
    });
  });

  it('rejects a CDN — configuration cannot widen the namespace registry', () => {
    withTemp({ entries: [{ uri: 'https://cdn.example.invalid/lib.js', reason: 'convenience' }] }, (file) => {
      expect(() => loadAllowlist(file)).toThrow(/not a recognised XML\/HTML namespace/);
    });
  });

  it('rejects a non-namespace path on the namespace HOST', () => {
    withTemp({ entries: [{ uri: 'https://www.w3.org/not-a-namespace.js', reason: 'looks official' }] }, (file) => {
      expect(() => loadAllowlist(file)).toThrow(/not a recognised XML\/HTML namespace/);
    });
  });

  it('rejects a userinfo form of a recognised namespace', () => {
    withTemp({ entries: [{ uri: 'http://user:<email>/2000/svg', reason: 'svg' }] }, (file) => {
      expect(() => loadAllowlist(file)).toThrow(/not a recognised XML\/HTML namespace/);
    });
  });

  it('rejects a duplicate entry', () => {
    const e = { uri: 'http://www.w3.org/2000/svg', reason: 'svg' };
    withTemp({ entries: [e, e] }, (file) => {
      expect(() => loadAllowlist(file)).toThrow(/duplicate/i);
    });
  });

  it('rejects an unexpected field', () => {
    withTemp({ entries: [{ uri: 'http://www.w3.org/2000/svg', reason: 'svg', force: true }] }, (file) => {
      expect(() => loadAllowlist(file)).toThrow(/unexpected field/);
    });
  });

  it('rejects a malformed document rather than allowing everything', () => {
    withTemp({ allow: [] }, (file) => {
      expect(() => loadAllowlist(file)).toThrow(/entries/);
    });
  });

  it('the shipped allowlist is a subset of the code-owned namespace registry, all with reasons', () => {
    const doc = JSON.parse(readFileSync(REAL_ALLOWLIST, 'utf8'));
    expect(doc.entries.length).toBeGreaterThan(0);
    for (const entry of doc.entries) {
      expect(RECOGNISED_NAMESPACE_URIS).toContain(entry.uri);
      expect(entry.reason.trim().length).toBeGreaterThan(0);
    }
  });

  it('every recognised namespace URI is a bare w3.org namespace, not a fetchable resource', () => {
    for (const uri of RECOGNISED_NAMESPACE_URIS) {
      const parsed = new URL(uri);
      expect(parsed.host).toBe('www.w3.org');
      expect(parsed.username).toBe('');
      expect(parsed.search).toBe('');
      expect(parsed.hash).toBe('');
    }
  });
});

describe('vendor URL neutralization (react-dom scoping + behaviour)', () => {
  // Faithful replica of react-dom's minified formatProdErrorMessage.
  const REACT_DOM_FIXTURE = 'function fmt(e){for(var t="https://reactjs.org/docs/error-decoder.html?invariant='
    + '"+e,n=1;n<arguments.length;n++)t+="&args[]="+encodeURIComponent(arguments[n]);'
    + 'return"Minified React error #"+e+"; visit "+t+" for the full message.";}';
  const REACT_DOM_ID = '/repo/client/node_modules/react-dom/cjs/react-dom.production.min.js';

  // eslint-disable-next-line no-new-func -- the fixture is defined above, not external input
  const evalFmt = (code) => new Function(`${code}; return fmt;`)();

  it('is scoped: a chunk WITHOUT react-dom is left untouched', () => {
    const result = applyNeutralizations(REACT_DOM_FIXTURE, ['/repo/client/src/App.tsx']);
    expect(result.applied).toEqual([]);
    expect(result.code).toBe(REACT_DOM_FIXTURE);
  });

  it('applies to a chunk containing react-dom, and removes the external origin', () => {
    const result = applyNeutralizations(REACT_DOM_FIXTURE, [REACT_DOM_ID]);
    expect(result.applied).toHaveLength(1);
    expect(result.code).not.toContain('reactjs.org');
    expect(scanText(result.code, 'js', allowed)).toEqual([]);
  });

  // Proves FORMATTING survives — the error code, invariant and args — not that decoding works.
  // No decoder route is served, so the code is preserved for manual lookup only.
  it('REGRESSION: the React error code, invariant and args survive message formatting', () => {
    const before = evalFmt(REACT_DOM_FIXTURE)(418, 'Foo', 'Bar');
    const after = evalFmt(applyNeutralizations(REACT_DOM_FIXTURE, [REACT_DOM_ID]).code)(418, 'Foo', 'Bar');

    // The invariant number, the args, and the message shape all survive…
    expect(after).toContain('Minified React error #418');
    expect(after).toContain('invariant=418');
    expect(after).toContain('&args[]=Foo');
    expect(after).toContain('&args[]=Bar');
    expect(after).toContain('for the full message.');
    // …and the ONLY difference is the origin that was removed.
    expect(before).toContain('https://reactjs.org/docs/error-decoder.html?invariant=418');
    expect(after).not.toContain('reactjs.org');
    expect(after).toBe(before.replace(
      'https://reactjs.org/docs/error-decoder.html?invariant=',
      'react-error-decoder?invariant=',
    ));
  });

  it('handles a Windows-style module id', () => {
    const result = applyNeutralizations(REACT_DOM_FIXTURE, ['C:\\repo\\node_modules\\react-dom\\index.js']);
    expect(result.applied).toHaveLength(1);
  });

  it('reports a rule that fired as not stale, and one that never fired as stale', () => {
    expect(staleRules(new Set(VENDOR_URL_NEUTRALIZATIONS.map((r) => r.find)))).toEqual([]);
    expect(staleRules(new Set())).toHaveLength(VENDOR_URL_NEUTRALIZATIONS.length);
  });

  it('every rule is scoped to a module and carries a reason', () => {
    for (const rule of VENDOR_URL_NEUTRALIZATIONS) {
      expect(rule.module).toMatch(/node_modules\//);
      expect(rule.reason.trim().length).toBeGreaterThan(0);
    }
  });
});

describe('scanDist', () => {
  it('walks a build directory, skips binaries, and reports file and line', () => {
    const dir = mkdtempSync(join(tmpdir(), 'aptr01-dist-'));
    try {
      mkdirSync(join(dir, 'assets'));
      writeFileSync(join(dir, 'index.html'), '<!doctype html><div id="root"></div>');
      writeFileSync(join(dir, 'assets', 'clean.js'), `${LICENCE_BANNER}${INLINE_SVG_PROPS}`);
      const font = Buffer.alloc(64);
      font.write('wOF2', 0, 'latin1');
      font.writeUInt32BE(64, 8);
      writeFileSync(join(dir, 'assets', 'font.woff2'), font);
      const clean = scanDist(dir, allowed);
      expect(clean.findings).toEqual([]);
      expect(clean.scanned).toBe(2);

      writeFileSync(join(dir, 'assets', 'dirty.js'), 'x\nfetch("https://example.invalid")');
      const dirty = scanDist(dir, allowed);
      expect(dirty.findings).toHaveLength(1);
      expect(dirty.findings[0]).toMatchObject({ line: 2, value: 'https://example.invalid' });
      expect(dirty.findings[0].file).toContain('dirty.js');
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe('the real built bundle', () => {
  const built = existsSync(DIST);
  const bundleJs = () => readdirSync(join(DIST, 'assets'))
    .filter((f) => f.endsWith('.js'))
    .map((f) => readFileSync(join(DIST, 'assets', f), 'utf8'))
    .join('\n');

  it.skipIf(!built)('is clean under the lint', () => {
    expect(scanDist(DIST, allowed).findings).toEqual([]);
  });

  it.skipIf(!built)('still carries both known false-positive sources, so the lint stays exercised', () => {
    const js = bundleJs();
    expect(js).toContain('http://www.w3.org/2000/svg'); // inline-SVG xmlns
    expect(js).toMatch(/\/\*![^*]*https?:\/\//); // licence banner carrying a URL
  });

  it.skipIf(!built)('carries no react-dom documentation origin', () => {
    const js = bundleJs();
    expect(js).not.toContain('reactjs.org');
    expect(js).toContain('react-error-decoder?invariant=');
  });
});
